title: "Suubodh Patil"
description: "Security Consultant Architect â€” SaaS, Compliance & Cloud"
theme: minima   # default theme, but you can swap
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
markdown: kramdown

# Branding options
author:
  name: "Suubodh Patil"
  email: "subodhpatil@outlook.com"
social_links:
  linkedin: "https://linkedin.com/in/subodhpatil"
  github: "https://github.com/subodhpatil"
